# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/teststudio-apis"
## The application virtual path
baseurl: "/teststudio-apis"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,run.cmd]
exclude_navigation: ["copyright.html"]


navigation:
# === Test Studio for APIs ===
    getting-started:
        title: "Getting Started"
        position: 2
    features:
        title: "Features"
        position: 3
    features/steps:
        title: "Steps"
        position: 1
    features/code-features:
        title: "Code Features"
        position: 2
    features/record:
        title: "Record"
        position: 2
    features/command-line:
        title: "Command Line Interface"
        position: 3
    features/import:
        title: "Import"
        position: 3
    features/authorization:
        title: "Authorization"
        position: 4
    advanced-topics:
        title: "Advanced Topics"
        position: 4
    troubleshooting-guide:
        title: "Troubleshooting Guide"
        position: 5

## The product name
productName: "Progress Telerik Test Studio for APIs"

# CTA Panels
has_cta_panels: true

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

product: "Progress Telerik Test Studio for APIs"
platform: "teststudio-apis"
main_theme: teststudio
has_api_reference: false
tabbed_code_marker_length: 3
edit_repo_url: https://github.com/telerik/teststudio/edit/master/docs-apitesting

productCode: TESTSTUDIOAPI

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:lxlmtcw2g-u'
gcs_api_key: 'AIzaSyBWT8yvj_DCdSX2bmLUbor5p0gqc9rWoLc'


download: https://www.telerik.com/download/teststudio-apis
nav:
  "Release History": https://www.telerik.com/support/whats-new/teststudio/release-history
  "About": https://www.telerik.com/teststudio-dev

footer:
-
  title: "Getting Started"
  links:
    "Installation": https://docs.telerik.com/teststudio-apis/getting-started/installation
    "Sample Project": https://docs.telerik.com/teststudio-apis/getting-started/sample-project
    "Whats New": "https://www.telerik.com/support/whats-new/teststudio"
    "Roadmap": https://www.telerik.com/support/whats-new/teststudio/roadmap
-
  title: "Community"
  links:
    "Feedback Portal": http://feedback.telerik.com/Project/182

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
