# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/teststudiodev"

## The application virtual path
baseurl: "/devtools/teststudiodev"

## The product name
productName: "Test Studio Dev Documentation"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock, docs-watcher/*]
exclude_navigation: ["copyright.html"]


## List your directory names and order here, like this:
navigation:
    prerequisites:
        title: Prerequisites
        position: 1
    
    code-in-test:
        title: Implement Code in Test
        position: 4
    
    code-in-test/element-identification:
        title: Element Identification
        position: 2

    code-in-test/html-control-suite:
        title: HTML Control Suite
        position: 3

    code-in-test/settings-and-configuration-wtc:
        title: Settings and Configuration
        position: 5
    
    code-in-test/silverlight-wpf-automation-wtc:
        title: WPF/Silverlight Automation
        position: 4

    code-in-test/advanced-topics-wtc:
        title: Advanced Topics
        position: 6

    code-in-test/advanced-topics-wtc/html-popups-and-dialogs-wtc:
        title: Popups and Dialogs
        position: 0

    code-in-test/advanced-topics-wtc/javascript-wtc:
        title: JavaScript
        position: 1

    code-in-test/advanced-topics-wtc/test-regions-wtc:
        title: Test Regions
        position: 2
    
    code-in-test/coded-samples:
        title: Coded Samples
        position: 7

    code-in-test/coded-samples/general:
        title: General
        position: 0

    code-in-test/coded-samples/html:
        title: HTML
        position: 1

    code-in-test/coded-samples/silverlight:
        title: Silverlight
        position: 2

    code-in-test/coded-samples/silverlight/combobox-automation:
        title: ComboBox Automatiion
        position: 0

    code-in-test/coded-samples/silverlight/radgridview-automation:
        title: RadGridView Automation
        position: 1

    code-in-test/coded-samples/wpf:
        title: WPF
        position: 3

    features:
        title: Features
        position: 6
    
    features/recorder:
        title: Recorder
        position: 1
    
    features/recorder/verifications:
        title: Verifications
        position: 5

    features/recorder/mouse-actions:
        title: Mouse Actions
        position: 6

    features/recorder/specific-recording-scenario:
        title: Recording Specifics
        position: 7

    features/elements-explorer:
        title: Elements Explorer
        position: 2

    features/test-execution:
        title: Test Execution
        position: 3

    features/failed-tests-debugging:
        title: Debug Failed Tests
        position: 4

    features/test-maintenance:
        title: Test Maintenance
        position: 5

    features/data-driven-testing:
        title: Data Driven Testing
        position: 6
    
    features/logical-steps:
        title: Logical Steps
        position: 7

    features/custom-steps:
        title: Custom Steps
        position: 8

    features/project-settings:
        title: Project Settings
        position: 9

    advanced-topics:
        title: Advanced Topics
        position: 7

    advanced-topics/installation:
        title: Installation
        position: 0

    advanced-topics/recording:
        title: Recording
        position: 1

    advanced-topics/elements:
        title: Elements
        position: 2

    advanced-topics/data-driven-testing:
        title: Data Driven Testing 
        position: 3

    advanced-topics/project-configuration:
        title: Project Configuration
        position: 4

    advanced-topics/ci:
        title: Continuous Integration
        position: 5

    ##scenarios:
      ##  title: Scenarios
      ##  position: 5

    ##integration:
      ##  title: Other Integrations
      ##  position: 8

    ##code-coverage:
       ## title: Code Coverage Integrations
       ## position: 7

    ##continuous-integration:
       ## title: Continuous Integration
       ## position: 6

    ##basic-usage/mock-behaviors:
      ##  title: Mock Behaviors
      ##  position: 2

    ##basic-usage/mock:
      ##  title: Mock
      ##  position: 3

## The application virtual path
baseurl: /devtools/teststudiodev


# CTA Panels
has_cta_panels: true


## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "teststudiodev"

        
## The Kendo UI version used
cdnVersion: "2017.3.1026"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

product: "Progress Telerik TestStudio Dev"
platform: "teststudiodev"
main_theme: teststudio
skip_tabbed_code: true
has_api_reference: false
edit_repo_url: https://github.com/telerik/teststudio/edit/master/docs-teststudiodev

productCode: TSDEVED

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:8yrsvynfbrc'
gcs_api_key: 'AIzaSyB4XlWMqTSFHUjITODwX6zkLDBgbi69N8g'

download: https://www.telerik.com/download-trial-file/v2-b/test-studio-dev-edition
nav:
  "Release History": https://www.telerik.com/support/whats-new/teststudio/release-history
  "About": https://www.telerik.com/teststudio-dev
  "Pricing": https://www.telerik.com/purchase.aspx

footer:
-
  title: "Getting Started"
  links:
    "Quickstart": https://docs.telerik.com/devtools/teststudiodev/quickstart
    "Videos": https://www.youtube.com/playlist?list=PLPd3ce5hn3ozSoFDKG4XElnE5nOQ6AyHd
    "Whats New": "https://www.telerik.com/support/whats-new/teststudio"
    "Roadmap": https://www.telerik.com/support/whats-new/teststudio/roadmap
-
  title: "Community"
  links:
    "Blogs": https://www.telerik.com/blogs/.net

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
